#!/usr/local/bin/bash
#Author: Luke Bechtel
#Supervisor: N/A
#Date: Thu, Feb 12 2015
#Summary:
#		Runs Dr. James Plank's gradescript in the current directory,
#   then compares correct and test stdout files produced (using sdiff)

usage()
{
cat << EOF
usage: $0 [-options (all one hyphen)] [problem number]
Runs Dr. James Plank's gradescript in the current directory,
then compares correct and test stdout files produced (using sdiff)

OPTIONS:
	-h      Show this message
	-e      Compare correct and test.
	-v      Verbose
EOF
}

SHOWERROR=0

while getopts hev: OPTION; do
	case "${OPTION}" in
		h)
			usage
			exit 1
			;;
		e)
			SHOWERROR=1
			;;
		v)
			VERBOSE=1
			;;
	esac
done

shift $(( OPTIND - 1 ))

if [[ -z $1 ]]; then
	usage
	exit 1
fi

./gradescript $1

if [ $SHOWERROR -ne 1 ]; then
	sdiff  tmp-$1-correct-stdout.txt tmp-$1-\test-stdout.txt
else
	sdiff  tmp-$1-correct-stderr.txt tmp-$1-\test-stderr.txt
fi
